version: '3.0'

services:
 postgres:
  build:
   context: .
   dockerfile: postgres.dockerfile
  container_name: postgres
  image: postgres:15.1-alpine
  environment:
   POSTGRES_DB: ${POSTGRES_DB}
   POSTGRES_USER: ${POSTGRES_USER}
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   PG_DATA: /var/lib/postgresql/data
  ports:
   - 5432:5432
  volumes:
   - pgdata:/var/lib/postgresql/data
  restart: always
 back:
  container_name: back
  build:
   context: ./Server
  env_file:
   - ./Server/.env
  volumes:
   - ./Server:/Server
   - /Server/node_modules
  ports:
   - 3001:3001
  command: npm run start
  depends_on:
   - postgres
  restart: always
 react-ui:
  build:
   context: ./Client
  env_file:
   - ./Client/.env
  ports:
   - 3002:3002
  container_name: react-ui
  depends_on:
   - back
  command: npm run start
  volumes:
   - ./Client:/Client
   - /Client/node_modules
  restart: always
  
volumes:
 pgdata: