version: '3.0'

services:
 postgres:
  container_name: postgres
  image: postgres:14.5
  env_file:
   - .env
  environment:
   PG_DATA: /var/lib/postgresql/data
  ports:
   - 5432:5432
  volumes:
   - pgdata:/var/lib/postgresql/data
  restart: always
 back:
  container_name: back
  build:
   context: .
  env_file:
   - .env
  volumes:
   - .:/app
   - /app/node_modules
  ports:
   - 5000:5000
   - 5001:5001
   - 9229:9229
  command: npm run start
  depends_on:
   - postgres
  restart: always
 react-ui:
  build:
   context: ../../zoom_quiz_client
  env_file:
   - ../../zoom_quiz_client/.env
  ports:
   - 3000:3000
  container_name: react-ui
  depends_on:
   - back
  command: npm run start
  volumes:
   - ../../zoom_quiz_client:/app
   - /app/node_modules
  restart: always
  
volumes:
 pgdata: